<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="all_staff.aspx.cs" MasterPageFile="~/ADMIN/Site1.Master"  Inherits="Stock_Inventory.ADMIN.all_staff" %>




<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">



	<title>Admin | all idp staffs</title>
	<meta charset="utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
	<!-- CSS -->
	<!-- CSS -->
 
	<link rel="stylesheet" href="assets/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="assets/css/vendor/icon-sets.css"/>
	<link rel="stylesheet" href="assets/css/main.min.css"/>
    <link href="assets/css/ui.jqgrid.min.css" rel="stylesheet" />

   
	<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
	<link rel="stylesheet" href="assets/css/demo.css"/>
	
 </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">




    <html xmlns="http://www.w3.org/1999/xhtml">

<body>
   

			<div class="main-content">
				<div class="container-fluid">
					<!-- OVERVIEW -->
					<div class="panel panel-headline">
						<div class="panel-heading">
							<p class="text-center background-muted" style="font-size: 20px; color: blue; font-family: 'Lato';"> Inventory manager's </p>
						</div>
						<div class="panel-body">
							<div class="row">
	
      
						    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                                ConnectionString="<%$ ConnectionStrings:inventoryConnectionString %>" 
                                ProviderName="<%$ ConnectionStrings:inventoryConnectionString.ProviderName %>" 
                                
                                    
                                    SelectCommand="SELECT s_id, s_fullname, s_gender, s_email, s_age FROM iv_staff WHERE (s_cat = ?)">
                                <SelectParameters>
                                    <asp:QueryStringParameter DefaultValue="inventory manager" Name="s_cat" 
                                        QueryStringField="inventory manager" Type="String" />
                                </SelectParameters>
                            </asp:SqlDataSource>
                               
                         <asp:GridView ID="GridView1" 
                                class="table table-responsive" runat="server" 
                                AllowSorting="True" DataSourceID="SqlDataSource1" 
                                AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" 
                                GridLines="None" Width="785px" AutoGenerateEditButton="True" 
                                Height="487px" AllowPaging="True" AutoGenerateDeleteButton="True" >
                                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                                <Columns>
                                    <asp:BoundField DataField="s_id" HeaderText="S/N" />
                                    <asp:BoundField DataField="s_fullname" HeaderText="Name" />
                                    <asp:BoundField DataField="s_gender" HeaderText="Gender" />
                                    <asp:BoundField DataField="s_email" HeaderText="Email" />
                                    <asp:BoundField DataField="s_age" HeaderText="Age" />
                                  
                                </Columns>
                                <EditRowStyle BackColor="#999999" />
                                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                            </asp:GridView>
						</div>	
     
                                  <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
                                ConnectionString="<%$ ConnectionStrings:inventoryConnectionString %>" 
                                ProviderName="<%$ ConnectionStrings:inventoryConnectionString.ProviderName %>" 
                                
                                    
                                    
                                    SelectCommand="SELECT s_id, s_fullname, s_gender, s_email, s_age FROM iv_staff WHERE (s_cat = ?)">
                                <SelectParameters>
                                    <asp:QueryStringParameter DefaultValue="manager" Name="s_cat" 
                                        QueryStringField="manager" Type="String" />
                                </SelectParameters>
                            </asp:SqlDataSource>
                               <p class="text-center background-muted" style="font-size: 20px; color: blue; font-family: 'Lato';">Manager's </p>
                       <asp:GridView ID="GridView2" CssClass="table table-responsive" 
                                 runat="server" 
                                AllowSorting="True" DataSourceID="SqlDataSource2" 
                                AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" 
                                GridLines="None" Width="785px" AutoGenerateEditButton="True" 
                                Height="487px" AllowPaging="True" AutoGenerateDeleteButton="True" >
                                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                                <Columns>
                                    <asp:BoundField DataField="s_id" HeaderText="S/N" />
                                    <asp:BoundField DataField="s_fullname" HeaderText="Name" />
                                    <asp:BoundField DataField="s_gender" HeaderText="Gender" />
                                    <asp:BoundField DataField="s_email" HeaderText="Email" />
                                    <asp:BoundField DataField="s_age" HeaderText="Age" />
                                  
                                </Columns>
                                <EditRowStyle BackColor="#999999" />
                                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                            </asp:GridView>
      
					</div>
					<!-- END OVERVIEW -->

				</div>
			</div>
			<!-- END MAIN CONTENT -->
			<footer>
				<div class="container-fluid">
					<p class="copyright">&copy; 2017. Designed by Ehimwenma </p>
				</div>
			</footer>
		</div>

	
</body>

    <script src="assets/js/jquery.jqGrid.min.js"></script>
    <script src="assets/js/jquery.dataTables.min.js"></script>
    <script src="assets/js/jquery.dataTables.bootstrap.min.js"></script>

</html>

    </asp:Content>